// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfnxrjJMqye6JSXT5X3rbgMUjhrh9JmfE',
    appId: '1:996014459125:web:525353cc5a18588d679dbc',
    messagingSenderId: '996014459125',
    projectId: 'tontinefacile237',
    authDomain: 'tontinefacile237.firebaseapp.com',
    storageBucket: 'tontinefacile237.firebasestorage.app',
    measurementId: 'G-M5WGH85PD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxNEAw4aFUxWIwpRwNtbUaalVTxEGyVtI',
    appId: '1:996014459125:android:7ddcc124f6405a92679dbc',
    messagingSenderId: '996014459125',
    projectId: 'tontinefacile237',
    storageBucket: 'tontinefacile237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdU3vqh_zwqA1ttlQqLcAdJr83mv4vDg4',
    appId: '1:996014459125:ios:da386779e2ce5429679dbc',
    messagingSenderId: '996014459125',
    projectId: 'tontinefacile237',
    storageBucket: 'tontinefacile237.firebasestorage.app',
    iosBundleId: 'com.example.tontinefacile',
  );
}
